server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/ProductDb?useSSL=false&serverTimezone=UTC
    username: root
    password: praise22
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL57InnoDBDialect
    hibernate:
      ddl-auto: update
  application:
    name: PRODUCT_SERVICE
  config:
    import: configserver:http://localhost:9296




#eureka:
#  instance:
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone:  ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}









